### ISSUE TITLE
feat: 최종 발표 데모

### ISSUE THREAD

**Issue by anjm1020** [MinSaMo/server#53]
## Sub-issue
- [x] #52 
- [x] #55 
- [x] #58 
- [x] caption 들어오는거 user chat으로 sending
- [x] caption 처리 끝나고 random interval ( 3~5 sec )
- [x] script emergency에서 subscription path 변경
- [x] emergency occur case : mail 전송
- [x] gpt sub-key 추가 생성
